version: "3"
services:
  broker:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    networks:
      - localnet
    ports:
      - "1883:1883"
      - "9001:9001"
  node-red:
    container_name: nodered
    depends_on:
      - broker
    image: nodered/node-red-docker
    volumes:
      - "./node-red:/data"
    user: "0"
    networks:
      - localnet
    ports:
      - "1880:1880"
networks:
  localnet:
